### ISSUE TITLE
Git modification time

### ISSUE THREAD

**Issue by antonio-one** [antonio-one/table_loader#11]
Discover if git preserves modification time of the files, and restores them on check out

**Comment by antonio-one** [comment]
The modify date is identical between a new file between the master branch and a newly checked out branch.
```
touch emptyfile.json
stat -x emptyfile.json | grep -i modify
Modify: Sat Dec  5 09:49:43 2020
git add emptyfile.json
git commit -m "testing modify date is retained"
git push
git checkout -b modify_date_test
stat -x emptyfile.json | grep -i modify
Modify: Sat Dec  5 09:49:43 2020
```

However, in the event the repo is cloned from a fork the modify date is not retained.
```
git clone https://github.com/antonio-two/table_loader
stat -x emptyfile.json | grep -i modify
Modify: Sat Dec  5 10:07:24 2020
```

Due to this the modify date of a local file should not be used for state comparison purposes.

**Comment by txomon** [comment]
Awesome work! Thanks!
