### ISSUE TITLE
Document backend attributes

### ISSUE THREAD

**Issue by antonio-one** [antonio-one/table_loader#12]
Document what attributes are available in the different backends (local, gcs, bigquery) and document what are the comparisons that need to be done between them to assert whether they are the same table or not

**Comment by antonio-one** [comment]
This is not including metadata such as description, labels and modification_date

### Local
schema
payload
payload_hash
rows

### GCS
payload_hash

### BQ
schema
rows

**Comment by txomon** [comment]
From your analysis in https://github.com/antonio-one/table_loader/issues/13 I believe we don't have a way to compare local and GBQ backends.

We could rely on partial stuff like schema or modification time, but the truth is that the schema doesn't represent the whole table, and the modification time from the analysis done in #11 is just not possible.

Another alternative would be to use labels in bigquery tables, but that sound like an actual hack, as these would remain the same after someone manually changes part of the contents of the table, hence not being a solution.

Does it sound OK to you to not let compare all three ways?

**Comment by antonio-one** [comment]
What if we added the modification time as a bq label and compare the modification time managed by bq and the one managed by table_loader and if they are not equal we assume that a manual change has happened?

**Comment by txomon** [comment]
Would you mind describing what attributes are compared between backends?

**Comment by antonio-one** [comment]
@txomon I added some attribute comparisons on the issue description above.

**Comment by txomon** [comment]
From the changes I see, can you confirm that:

  1. We are good on Local <=> GCS comparison
  1. It is possible to compare GCS <=> GBQ through the modified date
  1. There are two solutions (labels and payload hashing) being put forward in order to provide Local <=> GBQ.

Regarding the label solution how would we make the label store the same timestamp as its own modified time? Adding the label modifies the timestamp itself, doesn't it?

Therefore, the only way to compare Local <=> GBQ would be through payload hashing. Besides the matter of cost, I believe this is a very tricky comparison to implement, How do we hash GBQ tables and the local files so that the output is the same?

As a bottom line, I believe comparing local and GBQ is costly, tricky, and the result of knowing whether something has changed or not can be extracted indirectly through Local <=> GCS <=> GBQ

**Comment by antonio-one** [comment]
Good point RE timestamp label!!

In terms of hashing. We could:
1. Download the results of a `select HASHED_COLUMN from TABLE` query and therefore control the choice hashing algorithm.
2. Download the results of a `select FARM_FINGERPRINT(HASHED_COLUMN) from TABLE` and use the `Fingerprint64` function from the [open-source FarmHash library](https://github.com/google/farmhash) as per the [documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/hash_functions). 

There is no way to compare GCS with GBQ. Unless I missed something there are no common attributes other than the grid_id, hence the GBQ `payload_hash` suggestion.

If we don't want to go down the route of GBQ hashing, the only thing remaining is to rely on `local.payload_hash == gcs.payload_hash` and if they are different, execute the sync.

I guess the decision then is related to value vs effort/cost.

### Pros / Cons
#### Option 1
`+` It could work nicely for small datasets.
`+` Control over hashing algo.
`-` Will incur download costs.
`-` Maybe not so nice for large dimension tables (e.g ip2country).
`-` Potentially prone to connection errors.
`-` Won't scale and will slow-down the execution.
'-' Relatively easy to code

#### Option 2
'+' Solid open source algorithm we can use
'-' Will incur query costs.
'+' Assumed to be less time consuming than downloading a whole column from a table.
'+' No issues with scaling, bigquery can take care of it.
'-' A bit more effort to code and test
'-' Potential very low risk in the event Google decide to use a different library or a "closed" source algo.

**Comment by txomon** [comment]
To make sure that we are aligned:

* Do we agree that if possible a solution that relies on modified date would be the best?
* If not, what are the requirements we are taking into account to choose the solution?

**Comment by antonio-one** [comment]
- Probably not. If there was a waterproof modified_date we could propagate across all states then yes but I don't see it. We can't rely on github maintaining it and GBQ manages it itself. 
- I suppose the only requirement I would vote for at this stage would be correctness and that can only be done with schema and payload_hash. I would welcome any ideas.

**Comment by txomon** [comment]
Call notes:

 1. Lets have comparison between local <-> GCS <-> GBQ
 1. Later implement full-validation with hashing
