### ISSUE TITLE
Create and implement FilesystemGridRepository with add, get, list, remove

### ISSUE THREAD

**Issue by txomon** [antonio-one/table_loader#15]
The `FilesystemGridRepository` should provide the following methods:

 * `add`
 * `get`
 * `list`
 * `remove`

And should provide the following attributes of Grids:

 * `payload`
 * `payload_hash`
 * `schema`
 * `schema_hash`
 * `grid_id`

Additionally, if the `FilesystemGridRepository` is created with `FilesystemGridRepository(..., provide_last_modified=True)` is should set:

* `last_modified`

**Comment by antonio-one** [comment]
@txomon I think I will include `query` as an attribute to cover the view and materialised view use cases. 
We can think about metadata such as `description`, `labels`, `modification_date`, `refresh_enabled`, `refresh_interval` later. I'll add a new ticket so we don't forget.
